<a href="https://colab.research.google.com/github/MarinaSokolova111/OPDA/blob/main/%D0%9E%D0%9F%D0%94%D0%90_%D0%9B%D0%B5%D0%BA%D1%86%D0%B8%D1%8F_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Задача* *№1*

*При малых значения не рационально использовать NumPy, но при больших значаниях это необходимо для быстрой и эффективной работы.  *

1.6. Считайте 3 числа:
n - количество элементов матрицы
m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).
Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется
пустых мест.


In [1]:
import numpy as np
n = 6
m = 2
k = 3
a = np.arange(n)
Z = a.reshape(m, k)
print(type(Z))
print(Z)

<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]


In [2]:
n = 6
m = 2
k = 3

a = list(range(n))

if m*k == n:
    def group(iterable, count):
        return [iterable[i:i + count] for i in range(0, len(iterable), count)]
        
    b = group(a, k)
    print(type(b))

    for i in b:
        for g in i:
            print(g, end = ' ')
        print()

else:
    print('-------------------------------------------------')

<class 'list'>
0 1 2 
3 4 5 


In [3]:
import timeit 
import numpy as np

def time_py(size): 
    n = 9
    m = 3
    k = 3
    a = list(range(n))
    
    if m*k == n:
        def group(iterable, count):
            return [iterable[i:i + count] for i in range(0, len(iterable), count)]
    
        b = group(a, k)
        print(type(b))

        for i in b:
            for g in i:
                print(g, end = ' ')
            print()

    else:
        print('-------------------------------------------------')

def time_numpy(size):
    n = 9
    m = 3
    k = 3
    a = np.arange(n)
    Z = a.reshape(m, k)
    print(type(Z))
    print(Z)

if __name__ == '__main__': 
     
     # For smaller arrays
    #print('Array size: 1000') 

    start_time = timeit.default_timer();
    time_py(1000) 
    py_time_1 = timeit.default_timer() - start_time 

    start_time = timeit.default_timer(); 
    time_numpy(1000) 
    numpy_time_1 = timeit.default_timer() - start_time 
    
    # For large arrays 
    #print('Array size: 100 000 000') 

    start_time = timeit.default_timer(); 
    time_py(100000000) 
    py_time_2 = timeit.default_timer() - start_time 

    start_time = timeit.default_timer(); 
    time_numpy(100000000) 
    numpy_time_2 = timeit.default_timer() - start_time

<class 'list'>
0 1 2 
3 4 5 
6 7 8 
<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]
<class 'list'>
0 1 2 
3 4 5 
6 7 8 
<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
print('Py size: 1000') 
print(f'size 1000: время {py_time_1}')
print(f'size 1000: время {numpy_time_1}') 
print('------------------------------------------')
print('Numpy size: 100000000') 
print(f'size 100000000: время {py_time_2}') 
print(f'size 100000000: время {numpy_time_2}')

Py size: 1000
size 1000: время 0.0017954099994312855
size 1000: время 0.0006089090002205921
------------------------------------------
Numpy size: 100000000
size 100000000: время 0.002387819999967178
size 100000000: время 0.0008530400000381633


Вывод: При работе с матрицами и т.п. бессомненно удобнее, быстрее и эффективнее работать через Numpy. 